flip-in/scrap-it

app/models/badge.rb
app/models/category.rb
app/models/pickup.rb
app/models/reward.rb
app/models/user.rb

Need to create custom method for Pickup.rb

validations

---

app/controllers/pickups_controller.rb

Not sure about the Update... gonna have a teacher look at it ASAP

did the CRUD for pickups controller

---

app/models/user.rb

user model updated (was not pushed before)

Crash test models fixes

---

app/controllers/dashboards_controller.rb
app/controllers/pickups_controller.rb
app/models/user.rb
app/views/dashboards/_impact.html.erb
app/views/dashboards/_schedule.html.erb
app/views/dashboards/user_dashboard.html.erb

added some logic to the user_dashboard
added basic tabs to the user_dashboard
_should_ list all the user's previous pickups _and_ one of the user's upcoming pickups

added a dashboard skeleton

---

db/migrate/20200310103641_add_default_to_pickups_status.rb

added default status to pickups

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_new-pickup.scss
app/controllers/pickups_controller.rb
app/javascript/packs/application.js
app/views/dashboards/_schedule.html.erb
app/views/layouts/application.html.erb
app/views/pickups/new.html.erb
db/schema.rb

cleaned up flatpickr and added time of day and notes

---

Gemfile
Gemfile.lock
app/models/user.rb
config/initializers/geocoder.rb
db/migrate/20200311063720_add_coordinates_to_user.rb

Users address is now geocoded

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_pickup_card.scss
app/views/dashboards/_schedule.html.erb
app/views/dashboards/user_dashboard.html.erb

added a bunch to the schedule card

---

app/assets/stylesheets/pages/_rewards_partial.scss
app/views/dashboards/_rewards.html.erb

fixed the css on the points circle

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_progress_bar.scss
app/assets/stylesheets/components/_schedule_card.scss
app/assets/stylesheets/pages/_user_dashboard.scss
app/controllers/dashboards_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/progress_bar.js
app/views/dashboards/_schedule.html.erb
db/seeds.rb

Animated bar

---

app/controllers/pickups_controller.rb
app/views/dashboards/_user_rewards.html.erb

made it so that it shows if the points is equal to the reward as well

---

app/assets/stylesheets/pages/_driver_sign_in.scss
app/assets/stylesheets/pages/_index.scss
app/views/drivers/sessions/new.html.erb

Driverz login

---

app/views/drivers/sessions/new.html.erb
db/migrate/20200317033230_change_avatar_name.rb
db/schema.rb

Avatar column name changed to avatar_id + Driver Login is clearer

Avatar column name

---

app/controllers/pages_controller.rb
config/routes.rb

added a route for an about page
added a controller method for about in the pages controller
added a view: about.html.erb

added about

---

app/assets/stylesheets/pages/_driver_pickup.scss
app/controllers/pickups_controller.rb
app/models/pickup.rb
app/views/dashboards/_past_pickups.html.erb
app/views/pickups/_approve_pickup.html.erb
app/views/pickups/_form_pickup_feedback.html.erb

added some style

---

app/controllers/pages_controller.rb
app/models/user.rb
app/views/pages/qr.html.erb
config/routes.rb

users now have a static id page
login as user
localhost:300/qr/1
qr/user_id

user now has fixed qr code

---

app/views/pages/home.html.erb

fixed font awesome icon

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_profile.scss
app/controllers/pages_controller.rb
app/views/dashboards/user_dashboard.html.erb
app/views/pages/profile.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb

I added a user profile, you can check it out on the navbar -> profile

I added a user profile, you can check it out on the navbar -> profile

---

app/assets/stylesheets/pages/_driver_pickup.scss
app/views/pickups/review.html.erb
app/views/shared/_navbar.html.erb

there was a bug on mobile (only) for the driver review buttons
also includes the Lifetime Points for user.. Let me know if you  don't like it

fixed the display issue on the driver review

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_driver_dashboard.scss
app/assets/stylesheets/pages/_map.scss
app/views/dashboards/driver_dashboard.html.erb
app/views/pages/map.html.erb

added some style to the driver page and to the map
